# Lesson 10 activity: Pandas

## Learning Objectives

By the end of this activity, you will be able to:
- Create Pandas Series and DataFrames
- Load data from CSV files
- Perform basic data exploration and analysis
- Calculate descriptive statistics
- Filter and manipulate DataFrame data

## Tips

- **Creating DataFrames:** Use `pd.DataFrame(dictionary)` where dictionary keys become column names
- **Loading CSV files:** Use `pd.read_csv('filename.csv')`
- **Basic exploration:** Use `.head()`, `.tail()`, `.info()`, `.describe()`, and `.shape`
- **Filtering data:** Use conditions like `df[df['column'] > value]`
- **Column selection:** Use `df['column_name']` or `df[['col1', 'col2']]`
- **Adding columns:** Use `df['new_column'] = calculation`
- **Statistics:** Use `.mean()`, `.max()`, `.min()`, `.sum()` methods

**Remember:** Take your time with each step and test your code frequently!

In [2]:
import pandas as pd
import numpy as np

---
## Problem 1: Creating Your First DataFrame

**Scenario:** You're working at a bookstore and need to create a simple inventory system.

**Your Task:**
1. Create a DataFrame called `books_df` with the following data:
   - Book titles: ["Python Basics", "Data Science Handbook", "Web Development Guide"]
   - Authors: ["John Smith", "Jane Doe", "Mike Johnson"]
   - Prices: [29.99, 45.50, 35.00]
   - Stock: [15, 8, 12]

2. Display the DataFrame
3. Print the shape of the DataFrame
4. Display basic information about the DataFrame using `.info()`

In [19]:
# Step 1: Create the DataFrame

books_df = pd.DataFrame({
    'Title': ['Python Basics', 'Data Science Handbook', 'Web Development Guide'],
    'Author': ['John Smith', 'Jane Doe', 'Mike Johnson'],
    'Price': [29.99, 45.50, 35.00],
    'Stock': [15, 8, 12]
})

In [20]:
# Step 2: Display the DataFrame

books_df

                   Title        Author  Price  Stock
0          Python Basics    John Smith  29.99     15
1  Data Science Handbook      Jane Doe  45.50      8
2  Web Development Guide  Mike Johnson  35.00     12

In [21]:
# Step 3: Print the shape

print(books_df.shape)

(3, 4)

In [7]:
# Step 4: Display info

books_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   3 non-null      object
 1   Author  3 non-null      object
 2   Price   3 non-null      float64
 3   Stock   3 non-null      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 228.0+ bytes

---
## Problem 2: Loading and Exploring Student Data

**Scenario:** You're a teacher analyzing student performance data.

**Your Task:**
1. Load the `students.csv` file into a DataFrame called `students_df`
2. Display the first 3 rows using `.head()`
3. Display the last 2 rows using `.tail()`
4. Show descriptive statistics for numerical columns using `.describe()`
5. Find the average grade of all students

Students data file avalible for download here: [students.csv](https://raw.githubusercontent.com/gperdrizet/fullstack-2605/main/data/students.csv)

In [22]:
# Step 1: Load the CSV file

students_df = pd.read_csv('/workspaces/utd-aiml-coursework/data/students.csv')

In [23]:
# Step 2: Display first 3 rows

students_df.head(3)

      name  age  grade  subject
0    Alice   20     85     Math
1      Bob   19     92  Science
2  Charlie   21     78     Math

In [24]:
# Step 3: Display last 2 rows

students_df.tail(2)

    name  age  grade  subject
6  Grace   20     90     Math
7  Henry   21     87  Science

In [25]:
# Step 4: Show descriptive statistics

students_df.describe()

             age      grade
count   8.000000   8.000000
mean   20.250000  87.125000
std     1.035098   5.462535
min    19.000000  78.000000
25%    19.750000  84.250000
50%    20.000000  87.500000
75%    21.000000  90.500000
max    22.000000  95.000000

In [27]:
# Step 5: Calculate average

students_df['grade'].mean()

87.125

---
## Problem 3: Data Filtering and Selection

**Scenario:** Continue working with the student data to find specific information.

**Your Task:**
1. Display only the 'name' and 'grade' columns from `students_df`
2. Find all students who scored above 85
3. Find all students studying 'Math'
4. Find the highest grade in the dataset
5. Count how many students are in each subject

In [28]:
# Step 1: Display only name and grade columns

students_df[['name', 'grade']]

      name  grade
0    Alice     85
1      Bob     92
2  Charlie     78
3    Diana     88
4      Eva     95
5    Frank     82
6    Grace     90
7    Henry     87

In [29]:
# Step 2: Students with grades above 85

students_df[students_df['grade'] > 85]

    name  age  grade  subject
1    Bob   19     92  Science
3  Diana   20     88  Science
4    Eva   19     95     Math
6  Grace   20     90     Math
7  Henry   21     87  Science

In [30]:
# Step 3: Students studying Math

students_df[students_df['subject'] == 'Math']

      name  age  grade subject
0    Alice   20     85    Math
2  Charlie   21     78    Math
4      Eva   19     95    Math
6    Grace   20     90    Math

In [31]:
# Step 4: Highest grade

students_df['grade'].max()

95

In [32]:
# Step 5: Count students by subject

students_df['subject'].value_counts()

subject
Math       4
Science    4
Name: count, dtype: int64

---
## Problem 4: Sales Data Analysis

**Scenario:** You're analyzing sales data for an electronics store.

**Your Task:**
1. Load the `sales.csv` file into a DataFrame called `sales_df`
2. Calculate the total value for each product (price × quantity)
3. Add this as a new column called 'total_value' to the DataFrame
4. Find the product with the highest total value
5. Calculate the grand total of all sales

Sales data file avalible for download here: [sales.csv](https://raw.githubusercontent.com/gperdrizet/fullstack-2605/main/data/sales.csv)

In [34]:
# Step 1: Load the sales data

sales_df = pd.read_csv('/workspaces/utd-aiml-coursework/data/sales.csv')
sales_df.head()

      product   price  quantity        date
0      Laptop  999.99         5  2024-01-15
1       Mouse   25.50        20  2024-01-15
2    Keyboard   75.00        15  2024-01-16
3     Monitor  299.99         8  2024-01-16
4  Headphones   59.99        12  2024-01-17

In [35]:
# Step 2 & 3: Calculate total value and add as new column

sales_df['total_value'] = sales_df['price'] * sales_df['quantity']
sales_df

      product   price  quantity        date  total_value
0      Laptop  999.99         5  2024-01-15      4999.95
1       Mouse   25.50        20  2024-01-15       510.00
2    Keyboard   75.00        15  2024-01-16      1125.00
3     Monitor  299.99         8  2024-01-16      2399.92
4  Headphones   59.99        12  2024-01-17       719.88

In [36]:
# Step 4: Find product with highest total value

sales_df.loc[sales_df['total_value'].idxmax()]

product            Laptop
price              999.99
quantity                5
date           2024-01-15
total_value       4999.95
Name: 0, dtype: object

In [37]:
# Step 5: Calculate grand total of all sales

sales_df['total_value'].sum()

9754.749999999998

---
## Problem 5: Series Creation and Manipulation

**Scenario:** Create and work with Pandas Series for daily temperature data.

**Your Task:**
1. Create a Pandas Series called `temperatures` with the following data:
   - Values: [22, 25, 23, 26, 24, 27, 25]
   - Index: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
2. Find the temperature for Wednesday
3. Find days with temperature above 24 degrees
4. Calculate the average temperature for the week
5. Find the day with the highest temperature

In [38]:
# Step 1: Create the temperature series

temperatures = pd.Series(
    [22, 25, 23, 26, 24, 27, 25],
    index=['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
)
temperatures

Mon    22
Tue    25
Wed    23
Thu    26
Fri    24
Sat    27
Sun    25
dtype: int64

In [39]:
# Step 2: Temperature for Wednesday

temperatures['Wed']

23

In [40]:
# Step 3: Days with temperature above 24

temperatures[temperatures > 24]

Tue    25
Thu    26
Sat    27
Sun    25
dtype: int64

In [41]:
# Step 4: Average temperature

temperatures.mean()

24.571428571428573

In [42]:
# Step 5: Day with highest temperature

temperatures.idxmax()

'Sat'

---
## Reflection Questions

Please answer these questions after completing the activity:

1. **What is the difference between a Pandas Series and a DataFrame?**
   
   *Your answer:*

2. **What are the advantages of using Pandas over working with plain Python lists and dictionaries?**
   
   *Your answer:*

3. **Describe a real-world scenario where you might use the filtering techniques you learned in Problem 3.**
   
   *Your answer:*

4. **What did you find most challenging about working with Pandas in this activity?**
   
   *Your answer:*